- hosts: localhost
  vars:
    ansible_python_interpreter: /opt/homebrew/bin/python3
  vars_files:
    - host_vars/env.yaml
    - host_vars/mrc.yaml
    - host_vars/openrc.yaml
  gather_facts: true

  roles:
    - role: openstack-common
    - role: openstack-images
    # - role: openstack-volume
    # - role: openstack-security-group
    # - role: openstack-instance
    # - role: openstack-volume-snapshot

# Install Docker and CouchDB
- hosts: DataNodes
  vars_files:
    - host_vars/env.yaml
    - host_vars/couchdb.yaml
  gather_facts: true
  
  roles:
    - role: nodes-baseline
    - role: install-docker
    # - role: 