#Create Volume snapshot
- name: Create Volume snapshot
  os_volume_snapshot:
    state: present
    volume: '{{item.volume}}'
    display_name: "{{item.vol_name}}--{{lookup('pipe','date +%Y-%m-%d')}}"
    wait: yes
    timeout: 600
    force: yes
    availability_zone: '{{availability_zone}}'
  loop: '{{volumes}}'
